name: 'Asset Tracker'
on:
  pull_request_target:
    types: [opened, ready_for_review]
    branches: [ master ]

jobs:
  test_commentary:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.body }}
